--비밀번호찾기 질문

DROP TABLE QEUSTION
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_QUE;

CREATE TABLE QUESTION(
    SEQ NUMBER(1) PRIMARY KEY,
    TITLE VARCHAR2(50) NOT NULL
);

CREATE SEQUENCE SEQ_QUE
START WITH 1
INCREMENT BY 1;



--회원정보
DROP TABLE MEMBER
CASCADE CONSTRAINTS;

CREATE TABLE MEMBER(
    ID VARCHAR2(50) PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL,
    PWD VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(50) UNIQUE,
    PHONE VARCHAR2(50) NOT NULL,
    ANSWER VARCHAR2(50) NOT NULL,
    DEL NUMBER(1) NOT NULL,
    QUESTION NUMBER(1) NOT NULL,
    ADDRESS VARCHAR2(100) NOT NULL,
    AUTH NUMBER(1) NOT NULL
);

ALTER TABLE MEMBER
ADD CONSTRAINT FK_MEM_QUE FOREIGN KEY(QUESTION)
REFERENCES QUESTION(SEQ);   





--자유게시판 BBS

DROP TABLE BBS
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_BBS;

CREATE TABLE BBS(
    SEQ NUMBER(1) PRIMARY KEY,
    ID VARCHAR2(50) NOT NULL,
    TITLE VARCHAR2(200)NOT NULL,
    CONTENT VARCHAR2(4000)NOT NULL,
    REGDATE VARCHAR2(50) NOT NULL,
    READCOUNT NUMBER(10)NOT NULL,
    DEL NUMBER(1) NOT NULL,
    TNAME VARCHAR2(50)NOT NULL
);


CREATE SEQUENCE SEQ_BBS
START WITH 1
INCREMENT BY 1;


ALTER TABLE BBS
ADD CONSTRAINT FK_BBS_ID FOREIGN KEY(ID)
REFERENCES MEMBER(ID);   



--공지사항 NOTICE

DROP TABLE NOTICE
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_QUE;

CREATE TABLE NOTICE(
    SEQ NUMBER(1) PRIMARY KEY,
    ID VARCHAR2(50) NOT NULL,
    TITLE VARCHAR2(200)NOT NULL,
    CONTENT VARCHAR2(4000)NOT NULL,
    REGDATE VARCHAR2(50)NOT NULL,
    READCOUNT NUMBER(10) NOT NULL,
    DEL NUMBER(1) NOT NULL,
    TNAME VARCHAR2(50)NOT NULL
);

CREATE SEQUENCE SEQ_NOT
START WITH 1
INCREMENT BY 1;


ALTER TABLE NOTICE
ADD CONSTRAINT FK_NOT_ID FOREIGN KEY(ID)
REFERENCES MEMBER(ID);   




--페스티벌 위치 STATE

DROP TABLE STATE
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_STA;


CREATE TABLE STATE(
    SEQ NUMBER(8) PRIMARY KEY,
    FSEQ NUMBER(8) NOT NULL
);


CREATE SEQUENCE SEQ_STA
START WITH 1
INCREMENT BY 1;




--축제 FESTIVAL

DROP TABLE FESTIVAL
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_FES;

CREATE TABLE FESTIVAL(
    SEQ NUMBER(8) PRIMARY KEY,
    ID VARCHAR2(50) NOT NULL,
    TITLE VARCHAR2(200)NOT NULL,
    CONTENT VARCHAR2(4000)NOT NULL,
    SDATE VARCHAR2(50)NOT NULL,
    EDATE VARCHAR2(50)NOT NULL,
    PLACE VARCHAR2(200) NOT NULL,
    DEL NUMBER(1) NOT NULL,
    READCOUNT NUMBER(8) NOT NULL,
    THUMBNAIL VARCHAR2(50) NOT NULL,
    TNAME VARCHAR2(50) NOT NULL
);


CREATE SEQUENCE SEQ_FES
START WITH 1
INCREMENT BY 1;


ALTER TABLE FESTIVAL
ADD CONSTRAINT FK_FES_ID FOREIGN KEY(ID)
REFERENCES MEMBER(ID);   


--축제 후기 REVIEW


DROP TABLE REVIEW
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_REV;

CREATE TABLE REVIEW(
    SEQ NUMBER(8) PRIMARY KEY,
    ID VARCHAR2(50) NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT VARCHAR2(4000) NOT NULL,
    DEL NUMBER(1) NOT NULL,
    FSEQ NUMBER(8) NOT NULL,
    TNAME VARCHAR2(50) NOT NULL
);

CREATE SEQUENCE SEQ_REV
START WITH 1
INCREMENT BY 1;

ALTER TABLE REVIEW
ADD CONSTRAINT FK_REV_ID FOREIGN KEY(ID)
REFERENCES MEMBER(ID);   

ALTER TABLE REVIEW
ADD CONSTRAINT FK_REV_FSEQ FOREIGN KEY(FSEQ)
REFERENCES FESTIVAL(SEQ);   




--지역명소 LOCATION


DROP TABLE LOCATION
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_LOC;

CREATE TABLE LOCATION(
    SEQ NUMBER(8) PRIMARY KEY,
    ID VARCHAR2(50) NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT VARCHAR2(4000) NOT NULL,
    PLACE VARCHAR2(200) NOT NULL,
    DEL NUMBER(1) NOT NULL,
    THUMBNAIL VARCHAR2(50) NOT NULL,
    SUBNAME VARCHAR2(50) NOT NULL,
    TNAME VARCHAR2(50) NOT NULL
);

CREATE SEQUENCE SEQ_LOC
START WITH 1
INCREMENT BY 1;

ALTER TABLE LOCATION
ADD CONSTRAINT FK_LOC_ID FOREIGN KEY(ID)
REFERENCES MEMBER(ID);   




--고객센터 CUSTOM

DROP TABLE CUSTOM
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_CUS;

CREATE TABLE CUSTOM(
    SEQ NUMBER(8) PRIMARY KEY,
    ID VARCHAR2(50) NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT VARCHAR2(4000) NOT NULL,
    WDATE VARCHAR2(50) NOT NULL,
    PROGRESS NUMBER(1) NOT NULL,
    DEL NUMBER(1) NOT NULL,
    TNAME VARCHAR2(50) NOT NULL
);

CREATE SEQUENCE SEQ_CUS
START WITH 1
INCREMENT BY 1;

ALTER TABLE CUSTOM
ADD CONSTRAINT FK_CUS_ID FOREIGN KEY(ID)
REFERENCES MEMBER(ID);   




--모집 MEETING

DROP TABLE MEETING
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_MEE;

CREATE TABLE MEETING(
    SEQ NUMBER(8) PRIMARY KEY,
    ID VARCHAR2(50) NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT VARCHAR2(4000) NOT NULL,
    MEET_LOC NUMBER(8) NOT NULL,
    USERCNT NUMBER(10) NOT NULL,
    MAXCNT NUMBER(10) NOT NULL,
    DEL NUMBER(1) NOT NULL,
    EDATE VARCHAR2(50) NOT NULL,
    WDATE VARCHAR2(50) NOT NULL,
    PROGRESS NUMBER(1) NOT NULL,
    TNAME VARCHAR2(50) NOT NULL
);

CREATE SEQUENCE SEQ_MEE
START WITH 1
INCREMENT BY 1;

ALTER TABLE MEETING
ADD CONSTRAINT FK_MEE_ID FOREIGN KEY(ID)
REFERENCES MEMBER(ID);   

ALTER TABLE MEETING
ADD CONSTRAINT FK_MEE_LOC FOREIGN KEY(MEET_LOC)
REFERENCES FESTIVAL(SEQ);







--미팅장소 SUB_MEETING

DROP TABLE SUB_MEETING
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_SUB_MEE;


CREATE TABLE SUB_MEETING(
    SEQ NUMBER(8) PRIMARY KEY,
    PSEQ NUMBER(8) NOT NULL
);

CREATE SEQUENCE SEQ_SUB_MEE
START WITH 1
INCREMENT BY 1;

ALTER TABLE SUB_MEETING
ADD CONSTRAINT FK_MEE_PSEQ FOREIGN KEY(PSEQ)
REFERENCES MEETING(SEQ);   



   


--호텔 HOTEL

DROP TABLE HOTEL
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_HOT;



CREATE TABLE HOTEL(
    SEQ NUMBER(8) PRIMARY KEY,
    ID VARCHAR2(50) NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT VARCHAR2(4000) NOT NULL,
    PLACE VARCHAR2(200) NOT NULL,
    DEL NUMBER(1) NOT NULL,
    MAXCOUNT NUMBER(10) NOT NULL,
    THUMBNAIL VARCHAR2(50) NOT NULL,
    PRICE NUMBER(30) NOT NULL,
    TNAME VARCHAR2(50) NOT NULL
);

CREATE SEQUENCE SEQ_HOT
START WITH 1
INCREMENT BY 1;

ALTER TABLE HOTEL
ADD CONSTRAINT FK_HOT_ID FOREIGN KEY(ID)
REFERENCES MEMBER(ID);   




--호텔 예약 RESERVE

DROP TABLE RESERVE
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_RES;

CREATE TABLE RESERVE(
    SEQ NUMBER(8) PRIMARY KEY,
    ID VARCHAR2(50) NOT NULL,
    SDATE VARCHAR2(50) NOT NULL,
    EDATE VARCHAR2(50) NOT NULL,
    DEL NUMBER(1) NOT NULL,
    PSEQ NUMBER(8) NOT NULL
);

CREATE SEQUENCE SEQ_RES
START WITH 1
INCREMENT BY 1;

ALTER TABLE RESERVE
ADD CONSTRAINT FK_RES_ID FOREIGN KEY(ID)
REFERENCES MEMBER(ID);   

ALTER TABLE RESERVE
ADD CONSTRAINT FK_RES_PSEQ FOREIGN KEY(PSEQ)
REFERENCES HOTEL(SEQ);   


--댓글 REPLY


DROP TABLE REPLY
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_REP;

CREATE TABLE REPLY(
    SEQ NUMBER(1) PRIMARY KEY,
    PSEQ NUMBER(8) NOT NULL,
    TNAME VARCHAR2(50) NOT NULL,
    ID VARCHAR2(50) NOT NULL,
    CONTENT VARCHAR2(4000) NOT NULL,
    REF NUMBER(10) NOT NULL,
    STEP NUMBER(10) NOT NULL,
    WDATE VARCHAR2(50) NOT NULL,
    DEL NUMBER(1) NOT NULL,
    LOCK_ NUMBER(1) NOT NULL
);

CREATE SEQUENCE SEQ_REP
START WITH 1
INCREMENT BY 1;

ALTER TABLE REPLY
ADD CONSTRAINT FK_REP_ID FOREIGN KEY(ID)
REFERENCES MEMBER(ID);   





--파일 PDS

DROP TABLE PDS
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_PDS;

CREATE TABLE PDS(
    SEQ NUMBER(8) PRIMARY KEY,
    FILENAME_BF VARCHAR2(50),
    FILENAME_AF VARCHAR2(50),
    PSEQ NUMBER(8) NOT NULL,
    TNAME VARCHAR2(50) NOT NULL
);

CREATE SEQUENCE SEQ_PDS
START WITH 1
INCREMENT BY 1;

COMMIT;



-- 쇼핑몰
-- 제품 PRODUCT

DROP TABLE PRODUCT
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_PRODUCT;

CREATE TABLE PRODUCT(
   SEQ NUMBER(8) PRIMARY KEY,
   ID VARCHAR2(50) NOT NULL,
   TITLE VARCHAR2(200) NOT NULL,
   CONTENT VARCHAR2(4000) NOT NULL,
   THUMBNAIL VARCHAR2(50) NOT NULL,
   PCOUNT NUMBER(10) NOT NULL,
   WDATE VARCHAR2(50) NOT NULL,
   DEL NUMBER(1) NOT NULL,
   FSEQ NUMBER(8),
   PLACE VARCHAR2(200) NOT NULL,
   PRICE NUMBER(10) NOT NULL,
   TNAME VARCHAR2(50) NOT NULL
)

CREATE SEQUENCE SEQ_PRODUCT
START WITH 1
INCREMENT BY 1;

ALTER TABLE PRODUCT
ADD CONSTRAINT FK_PRODUCT_ID FOREIGN KEY(ID)
REFERENCES MEMBER(ID);


SELECT * FROM CART

-- 장바구니 CART

DROP TABLE CART
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_CART;

CREATE TABLE CART(
   SEQ NUMBER(8) PRIMARY KEY,
   ID VARCHAR2(50) NOT NULL,
   PSEQ NUMBER(8) NOT NULL,
   MYCOUNT NUMBER(10) NOT NULL,
   OSEQ NUMBER(1) NOT NULL
);

CREATE SEQUENCE SEQ_CART
START WITH 1
INCREMENT BY 1;

ALTER TABLE CART
ADD CONSTRAINT FK_CART_ID FOREIGN KEY(ID)
REFERENCES MEMBER(ID);

ALTER TABLE CART
ADD CONSTRAINT FK_CART_PSEQ FOREIGN KEY(PSEQ)
REFERENCES PRODUCT(SEQ);

ALTER TABLE CART DROP CONSTRAINT FK_CART_ID CASCADE

-- 파일 다중용
-- 위의 pds와 같은듯.
DROP TABLE FILEPDS
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_FILEPDS;

CREATE TABLE FILEPDS (
    SEQ NUMBER(8) PRIMARY KEY,
    FILENAMEBF VARCHAR2(50) NOT NULL,
    FILENAMEAF VARCHAR2(50) NOT NULL,
    PSEQ NUMBER(8) NOT NULL,
    TNAME VARCHAR2(50) NOT NULL
);

CREATE SEQUENCE SEQ_FILEPDS
START WITH 1
INCREMENT BY 1;

--ALTER TABLE FILEPDS
--ADD CONSTRAINT FK_FILEPDS_PSEQ FOREIGN KEY(PSEQ)
--REFERENCES CART(SEQ);

ALTER TABLE FILEPDS DROP CONSTRAINT FK_FILEPDS_PSEQ CASCADE;
SELECT * FROM ALL_CONSTRAINTS WHERE TABLE_NAME='FILEPDS';


--주문내역 테이블 ORDER
DROP TABLE ORDERED
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_ORDERED;

CREATE TABLE ORDERED (
	SEQ NUMBER(8) PRIMARY KEY,
	OID VARCHAR2(50) NOT NULL,
	ONAME VARCHAR2(50) NOT NULL,
	OPHONE VARCHAR2(50) NOT NULL,
	OADDRESS VARCHAR2(100) NOT NULL,
	ODATE VARCHAR2(50) NOT NULL,
	OTPRICE NUMBER(10) NOT NULL
);

CREATE SEQUENCE SEQ_ORDERED
START WITH 1
INCREMENT BY 1;

ALTER TABLE ORDERED
ADD CONSTRAINT FK_ORDERED_ID FOREIGN KEY(OID)
REFERENCES MEMBER(ID);



COMMIT;

INSERT INTO QUESTION(SEQ,TITLE)
VALUES (SEQ_QUE.NEXTVAL, '니이름세글자는?');

INSERT INTO MEMBER(
   ID,PWD,NAME,EMAIL,PHONE,
   ANSWER,ADDRESS,
   QUESTION,DEL,AUTH)
VALUES(
   'admin','admin','관리자','admin@naver.com','010-1111-2222',
   'admin','admin시 admin동 admin호',
   1,0,1);
   
INSERT INTO MEMBER(
   ID,PWD,NAME,EMAIL,PHONE,
   ANSWER,ADDRESS,
   QUESTION,DEL,AUTH)
VALUES(
   'aaa','111','에이에이','aaa@naver.com','010-2222-2423',
   'aaa','aaa시 aaaa동 aaaaa호',
   1,0,0);

select * from member;

INSERT INTO FESTIVAL(SEQ, ID, TITLE, CONTENT, SDATE, EDATE, PLACE, DEL , READCOUNT, THUMBNAIL, TNAME )
VALUES(SEQ_FES.nextval,'admin','사과축제', '사과축제입니당','20190501','20190601','강원도 춘천시',0,0,'not_exsit','FESTIVAL');

INSERT INTO FESTIVAL(SEQ, ID, TITLE, CONTENT, SDATE, EDATE, PLACE, DEL , READCOUNT, THUMBNAIL, TNAME )
VALUES(SEQ_FES.nextval,'admin','사과 아이스크림 축제', '사과콘을 맛보세요','20190504','20190621','경상도 의성시',0,0,'not_exsit','FESTIVAL');

SELECT C.SEQ,C.ID,C.PSEQ,C.MYCOUNT,C.DEL,TITLE,CONTENT,THUMBNAIL,PCOUNT,WDATE,DEL,FSEQ,PLACE,PRICE,TNAME
FROM CART C, PRODUCT P
WHERE C.PSEQ = P.SEQ
AND C.ID='aaa'
AND C.DEL=0

select * from cart;

SELECT *
FROM CART
WHERE ID='aaa'
AND PSEQ=5
AND C.DEL=0

